#!/bin/sh
set -e

# If the package is removed, purged or installation is aborted, try to
# remove the default mountpoints.
#
# Failure to do so is not considered fatal, because they may be in use by
# the system administrator or some other daemon on the system.
if [ "$1" = remove -o "$1" = abort-install -o "$1" = purge ]; then
    rm -f /media/usb 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24; do
	rmdir /media/usb$i 2> /dev/null || :
    done
fi

#DEBHELPER#

exit 0
