#!/bin/sh
set -e

# If the package is installed, try to create the default mountpoints.
# Failure to do so is not considered fatal.
if [ "$1" = install ]; then
    mkdir /media 2> /dev/null || :
    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24; do
	mkdir /media/usb$i 2> /dev/null || :
    done
    ln -s usb0 /media/usb 2> /dev/null || :
fi

#DEBHELPER#

exit 0
